INSERT INTO `persona` (`nombre`,`tipo`) VALUES ("Devia Jose Luis","PF");
INSERT INTO `persona` (`nombre`,`tipo`) VALUES ("Devia Lorena Daniela","PF");
INSERT INTO `persona` (`nombre`,`tipo`) VALUES ("Devia Jesus Orlando","PF");
INSERT INTO `persona` (`nombre`,`tipo`) VALUES ("Barry Demián","PF");
INSERT INTO `persona` (`nombre`,`tipo`) VALUES ("Scioli Daniel","PF");
INSERT INTO `persona` (`nombre`,`tipo`) VALUES ("Macri Mauricio","PF");
INSERT INTO `persona` (`nombre`,`tipo`) VALUES ("de79sjakjakieioajdljsljjljdsowiowislklklklwoieoioxioasioeioiwoiosioiaoiowioieis","PF");
INSERT INTO `persona` (`nombre`,`tipo`) VALUES ("de80ekjrkjrkjkjmnbsjhjhjhaiuiuiuiuiuwiudiuiucjbjashhiiauoaioaiaoioaiaoiaoihjsgsh","PF");
INSERT INTO `persona` (`nombre`,`tipo`) VALUES ("de80ssjakjakieioajdljsljjljdsowiowislklklklwoieoioxioasioeioiwoiosioiaoiowvvvddd","PF, PJ");
INSERT INTO `persona` (`nombre`,`tipo`) VALUES ("Messi Lionel","PF");
INSERT INTO `persona` (`nombre`,`tipo`) VALUES ("Aluar S.A","PJ");
INSERT INTO `persona` (`nombre`,`tipo`) VALUES ("Infa S.A","PJ");
INSERT INTO `persona` (`nombre`,`tipo`) VALUES ("Municipalidad de Puerto Madryn","PJ");
INSERT INTO `persona` (`nombre`,`tipo`) VALUES ("Universidad Nacional de la Patagonia San Juan Bosco","PJ");
INSERT INTO `persona` (`nombre`,`tipo`) VALUES ("Milicic S.A","PJ");
INSERT INTO `persona` (`nombre`,`tipo`) VALUES ("Electroingenieria S.A","PJ");
INSERT INTO `persona` (`nombre`,`tipo`) VALUES ("CONICET Puerto Madryn","PJ");
INSERT INTO `persona` (`nombre`,`tipo`) VALUES ("Aerolineas Argentinas S.A","PJ");
INSERT INTO `persona` (`nombre`,`tipo`) VALUES ("YPF S.A","PJ");
INSERT INTO `persona` (`nombre`,`tipo`) VALUES ("Halliburton S.A","PJ");

INSERT INTO `identificador` (`tipo`,`valor`,`personaId`) VALUES ("MATRICULA","69859394341721728372939111426",1);
INSERT INTO `identificador` (`tipo`,`valor`,`personaId`) VALUES ("DNI","38268973114939692925517037921",2);
INSERT INTO `identificador` (`tipo`,`valor`,`personaId`) VALUES ("DNI","96151323364014823189973622018",3);
INSERT INTO `identificador` (`tipo`,`valor`,`personaId`) VALUES ("LEGAJO","91647699839583294415401518288",4);
INSERT INTO `identificador` (`tipo`,`valor`,`personaId`) VALUES ("CUIL","64321497163236333909946241296",5);
INSERT INTO `identificador` (`tipo`,`valor`,`personaId`) VALUES ("DNI","57988446454217950193615382648",6);
INSERT INTO `identificador` (`tipo`,`valor`,`personaId`) VALUES ("CUIL","39201483782315376226457875461",7);
INSERT INTO `identificador` (`tipo`,`valor`,`personaId`) VALUES ("CUIL","12625187875663860751407457922",8);
INSERT INTO `identificador` (`tipo`,`valor`,`personaId`) VALUES ("DNI","17653575483260928966745557545",9);
INSERT INTO `identificador` (`tipo`,`valor`,`personaId`) VALUES ("MATRICULA","26158923369651272152684156557",10);
INSERT INTO `identificador` (`tipo`,`valor`,`personaId`) VALUES ("CUIT","47319483379074929318526663391",11);
INSERT INTO `identificador` (`tipo`,`valor`,`personaId`) VALUES ("CUIT","29687589855666613761868519251",12);
INSERT INTO `identificador` (`tipo`,`valor`,`personaId`) VALUES ("CUIT","60213984962911661135979536794",13);
INSERT INTO `identificador` (`tipo`,`valor`,`personaId`) VALUES ("CUIT","16402573955069121743328879219",14);
INSERT INTO `identificador` (`tipo`,`valor`,`personaId`) VALUES ("CUIT","12783359497320763551609544757",15);
INSERT INTO `identificador` (`tipo`,`valor`,`personaId`) VALUES ("CUIT","93548391733421822771724722699",16);
INSERT INTO `identificador` (`tipo`,`valor`,`personaId`) VALUES ("CUIT","15712707566127678317333888584",17);
INSERT INTO `identificador` (`tipo`,`valor`,`personaId`) VALUES ("CUIT","69593543181629630574942786744",18);
INSERT INTO `identificador` (`tipo`,`valor`,`personaId`) VALUES ("CUIT","12362767918070866773757039216",19);
INSERT INTO `identificador` (`tipo`,`valor`,`personaId`) VALUES ("CUIT","87723879978389544991673568097",20);

INSERT INTO `datos_de_contacto` (`tipo`,`valor`,`personaId`) VALUES ("RED_SOCIAL","qUxabuCOuizoeAVIFEOOVIREroNAyoaojAHOLirEeoHIPOHUronoduEEueciUaXUCArutUaIAIQIPICOIAvInobiTACIJAwAnEG",1);
INSERT INTO `datos_de_contacto` (`tipo`,`valor`,`personaId`) VALUES ("TEL_CELULAR","piBEaOtIAaioUUMoEaWIheUEeeMUnOXENoNEaumUAegaDEIIluiEGoHeVUIiEoDIsEtavanAdUfeGIuEnIxiUezelAGIUiuoiIy",2);
INSERT INTO `datos_de_contacto` (`tipo`,`valor`,`personaId`) VALUES ("TEL_FIJO","wafuyeiuGaMoeePApuXOneCobaFAEOpIiEIAmAVeDOWeUOoeWOOInEEaJUNUFeNEWeMOWIQUeuiOkInepAvEDAyeoAjEcUoEmel",3);
INSERT INTO `datos_de_contacto` (`tipo`,`valor`,`personaId`) VALUES ("FAX","ZUVagUcOXEEAUiaujEpEMIdiRUVOnIfIPUaUeAroNOlUHEdiNiBAJArAzEBAGIVUVeserEdoBEwUOawERurigiCAcIuONunAXUZ",4);
INSERT INTO `datos_de_contacto` (`tipo`,`valor`,`personaId`) VALUES ("RED_SOCIAL","teouxEXUquBiKuhOFUgaGuOAFUSASUEUsuHaMAgojEmIIepUPIweMoseCOqoDoKovIKuVEBEwIkEIAmIRoPUSuviuuTokedUmUq",5);
INSERT INTO `datos_de_contacto` (`tipo`,`valor`,`personaId`) VALUES ("TEL_FIJO","oEpEdOguyiJAnemiuAOeKoKinulefaWUEeIAUoqoTEkEGUsikuXiwEIUvicUYiIoUoDONiEUyUPIyUHeKiYAnejAHoWEeojoPEH",6);
INSERT INTO `datos_de_contacto` (`tipo`,`valor`,`personaId`) VALUES ("EMAIL","BULEoOaEpeooKAfOIozaVevoUAAoyakoqONIJEYojINItoaUleVaVeKaRiCUxEquMiKiTEuuXAceXaLikoREHayavONotIZaxeA",7);
INSERT INTO `datos_de_contacto` (`tipo`,`valor`,`personaId`) VALUES ("TEL_FIJO","xExUGAsoyAkobeuaxUbatiqEZAtEWuFEfaQABAkoguaahUOIiIKIxerEvOYIYauIuuLOOAoUQIEozaiIUiiasowULijatomaNAs",8);
INSERT INTO `datos_de_contacto` (`tipo`,`valor`,`personaId`) VALUES ("FAX","ZovEPEhodOAUOOFikipIeUXeeEsOCUhatAhIFivaPEPonuBEXOroqoAIEOvEzoRaPigIZocUHIxOLOWAjIxiwuQulAuoeoZoiEg",9);
INSERT INTO `datos_de_contacto` (`tipo`,`valor`,`personaId`) VALUES ("TEL_CELULAR","DeiEBUNiXeWAwoyUaEsudAuusiZeCoLEViwuHoEEauZEdaYEjuzEXaaAFipaLOjUtIQeZUoEXAAudAFUMEGiCokAFERAZIoUgoC",10);
INSERT INTO `datos_de_contacto` (`tipo`,`valor`,`personaId`) VALUES ("RED_SOCIAL","YuvOpIAeNiYoFesetObujaMaDIjERaSOruHoHetIwIaIDaRIZIfaLEXOIExIJIpEzoRUpiFoFueucUTuHuEeFiYOqAkopuQiDoR",11);
INSERT INTO `datos_de_contacto` (`tipo`,`valor`,`personaId`) VALUES ("EMAIL","QaReoEJEJaDeYeeOjaKagEfiKEbiBIjeHufOfIxinuXifEQaCAXuKEqELiToiiEafEeaRegIlAtoSUmAxitOYiTALIeiaOQIHOg",12);
INSERT INTO `datos_de_contacto` (`tipo`,`valor`,`personaId`) VALUES ("EMAIL","WUOIzAfiKUGOLELiXIBeGupAwIAiyiDOjIEomiOAyisEcIkitIeOHuWAOakIYAhiDAkuIuxEIotaaAKExaDOZePizicaheAonuQ",13);
INSERT INTO `datos_de_contacto` (`tipo`,`valor`,`personaId`) VALUES ("FAX","aiPEQIduMAWiYEfowUkUSEvoPifuOADeIICIzemOGUQaIeXOhUHESARIoOfEtIBelUxEKiUuRuUibIiIFolOlEiAsiuAOoUuhOz",14);
INSERT INTO `datos_de_contacto` (`tipo`,`valor`,`personaId`) VALUES ("WEB","qatIDafuMAIaKiQIhIoAviniVAIavUnerEiAKInaAOiojuwuIuqomiPEgIxAbAnexuxEnuwelojIReTUoizoGAsAAeVeWiqUNul",15);
INSERT INTO `datos_de_contacto` (`tipo`,`valor`,`personaId`) VALUES ("TEL_FIJO","yIdeaoliUIZaYEWicOpAKAWazOeonoSixIHEjIUINohUGEaejiLujiOOuiFinuUoAAxiAUGOKOxiyinOuUcuiuQeyIdElUpeuuC",16);
INSERT INTO `datos_de_contacto` (`tipo`,`valor`,`personaId`) VALUES ("TEL_FIJO","kaDIceKIhAYAGubucAvOieIAEowINeNICEeoTuMOUaOajogaiiOoGihuRoOAzAAIzEKALOXEwehiiIyAzecArUdELAdayusUbOi",17);
INSERT INTO `datos_de_contacto` (`tipo`,`valor`,`personaId`) VALUES ("WEB","ZAQIfIiAnEgoEuCAKErijoTaiEEeYuTojEPaxOEEGetomeOIeoQiAurUiivAnOmIhibOBiREPApiIoVISObEdoDavIEOIIgUPEl",18);
INSERT INTO `datos_de_contacto` (`tipo`,`valor`,`personaId`) VALUES ("RED_SOCIAL","ZaNIgaMACiToDENuXiTosaJUXUAIJAFaiUmaQiAuMIcaGOUefIBaoonEfobogOtUfEKOQijeniMojOIIsaJAaAgegIAaWupIMOB",19);
INSERT INTO `datos_de_contacto` (`tipo`,`valor`,`personaId`) VALUES ("WEB","duPEZEuUnUfaAARuWowebOqiUiSAKIYeXoyuxonUnIWoNAdUNoHoOiHiwUvueaaobUUIFOBijiOIwEqUFemopuIaQekUWOBodAb",20);

INSERT INTO `domicilio` (`altura`,`calle`,`codPostal`,`localidad`,`num_dpto`,`num_piso`,`provincia`,`personaId`) VALUES ("158154","kAKOvecUuuHANaTiiiqoSOYOGuhibONAkIjiwOcOSUCUUoiei","76927","AonIzULeGAgOTiaiFejOcEmowAkEtUZemaBujUguiuhIHaxei","137","372","uOSOqEMIkUtInOVuNewoieQoyaCAsifUlixUIIjUuapoaaHaU",1);
INSERT INTO `domicilio` (`altura`,`calle`,`codPostal`,`localidad`,`num_dpto`,`num_piso`,`provincia`,`personaId`) VALUES ("601648","wOLafEMuSEuoNahooiaizaIAbUkIkAqIdocIbujiHIEEZoqoI","74166","QeaOluHIrasoREWAmafeBaOiTESaFUDeaajImuCieoNUsIAEO","338","203","HIlaPoIOJusoIifuQoaABeqipILaeeFasIaUvEuAVUgALeiAe",2);
INSERT INTO `domicilio` (`altura`,`calle`,`codPostal`,`localidad`,`num_dpto`,`num_piso`,`provincia`,`personaId`) VALUES ("643460","EiFaiODoTimufIFegIlIuisOyapeyAKemAKiwiHUnokisIAiU","76458","kocuIElEqiNAZOAiRAuOSiPoYOeeQOAAgaZEMIZAaELiaIrAU","725","019","NEqAzEeiYUWiDUoeAabEjeHOgaeUtaWAuUqEtIFEAuFohIsui",3);
INSERT INTO `domicilio` (`altura`,`calle`,`codPostal`,`localidad`,`num_dpto`,`num_piso`,`provincia`,`personaId`) VALUES ("159459","guDoFuRAZiQIKUpacOtArEvEREaEsUXoGuhadAkAQatepOxou","70776","aEAomADEMeZirEOOpagASaAigeiaqOTepomEOucIOUKUxIQoI","843","783","GoOUyABuoAHiYukIUEKAqAtojIpuwuBEmuyahIeexAjatuDUu",4);
INSERT INTO `domicilio` (`altura`,`calle`,`codPostal`,`localidad`,`num_dpto`,`num_piso`,`provincia`,`personaId`) VALUES ("168861","JIviQOWaAOKOnALOGiYucuPavoneaaViKEAEHoJIXioAWehEA","13515","BEAOgoUEjobaJuIAWIhOLIgokeCAoEVAHUAOzUUueOfaduHeU","249","719","UOjiBOLUlURoeURUNENAroaUKUCiqogORoNujapezUoiQEzAu",5);
INSERT INTO `domicilio` (`altura`,`calle`,`codPostal`,`localidad`,`num_dpto`,`num_piso`,`provincia`,`personaId`) VALUES ("907651","EUzUGEPoqotUIoRIeawaloOouubIVadorIKeNIJOuOtEiijiu","61458","FeDUQUSOWEmuQeGOcoLeJAUeSIOUaEVOgEKInUrISEGIioCiU","134","828","REvAJanAWooEgiXAIIDidiKomiLimEGawieABaCiJiNioUHio",6);
INSERT INTO `domicilio` (`altura`,`calle`,`codPostal`,`localidad`,`num_dpto`,`num_piso`,`provincia`,`personaId`) VALUES ("665889","HOIusUAAnEzoEakANelIlugOAIJITOXosOkuKeCugaGIBAcuo","64407","raZoIaPUwihoKEFEFocoDetIuOguGUKoUuYiOUEadUFuzEhIa","513","305","wipaXOmAqUpIpEqaginEaEbaqOpAcIHUNogeneGeDeaETauOE",7);
INSERT INTO `domicilio` (`altura`,`calle`,`codPostal`,`localidad`,`num_dpto`,`num_piso`,`provincia`,`personaId`) VALUES ("181061","AUDUbAFUQIWaVeWuaOwEZavAGoYekOwedAkeVEkuJoHEvImII","82538","tuSetEfIRaeoNOTEGUWEaoKAieiEcEtaXUliputAxaDuoIgOa","784","956","ianAxeFuAAjiMoAAmEYAuoAAzUcAFEROOaHowusuSeBorAhiU",8);
INSERT INTO `domicilio` (`altura`,`calle`,`codPostal`,`localidad`,`num_dpto`,`num_piso`,`provincia`,`personaId`) VALUES ("643953","jIzAcUSiyiDIdiuuweLURagAtiTuUIIuXUNawaLUuiWICESEu","50321","fEZoAuqAYoAEqUdAkOFOWEEEBiLoHeGEbAEOLoQivAIEveaAA","305","434","JojuYOBEnAxaYokuDIlIxEyixUwUFovAjOJoCEPuhiXOFExaa",9);
INSERT INTO `domicilio` (`altura`,`calle`,`codPostal`,`localidad`,`num_dpto`,`num_piso`,`provincia`,`personaId`) VALUES ("892283","uOPIMeqoJIgoFeBuAIqEDetuPanoiOrIqOBIToDiVAGameOei","89387","rIRUbITAfuRiXeYoIOBuxIHIWocieuiAhiuiGIBiUeoAjeIoI","378","166","buNoqAlagEGEUomuVeUEeEBAkoJEkAZodoxUgOYIsIjoMUiII",10);
INSERT INTO `domicilio` (`altura`,`calle`,`codPostal`,`localidad`,`num_dpto`,`num_piso`,`provincia`,`personaId`) VALUES ("706592","facuYiwUkIniTEiAqoaiSItAMaoiFEyowuXeKaVESaPoQEcAo","15637","VieITONoVIbesUNiqOriZIgOEoOEeayawOrIkEfEfOmEaOBEE","652","033","iaBujeEAwImIAELOUuweqoJivifuAeSauoQEPEvIEOGIRehuI",11);
INSERT INTO `domicilio` (`altura`,`calle`,`codPostal`,`localidad`,`num_dpto`,`num_piso`,`provincia`,`personaId`) VALUES ("493329","sIzeGOUobizUqIXaiIqETASexOGipAPEvipedoaibuNOqeQeU","60247","zukeUONAvOwIPoTuDOPoxoqAZIjImoRIUUxaYUsunAnusofuO","058","793","uAyeoOXokuwAcOOovacIxodaQUoOsokEOiBajiaimaZUiIpIo",12);
INSERT INTO `domicilio` (`altura`,`calle`,`codPostal`,`localidad`,`num_dpto`,`num_piso`,`provincia`,`personaId`) VALUES ("273045","iUherERoAoDidOgiViXOzUGoJiVelisUzOEIxUhEjidORoiUO","60552","nAwERuJulihaKubenEliOIdovaKIWOzuMIUEkIkUEAPeoaWOi","388","679","TuOEcadooanoaiuUXUkUaAqOoofIJItaLITUSoCiNEZALEyoe",13);
INSERT INTO `domicilio` (`altura`,`calle`,`codPostal`,`localidad`,`num_dpto`,`num_piso`,`provincia`,`personaId`) VALUES ("939189","DAmoNUiAVisIXUZuSIyiDAqiViRIMoQIAAMIOaDEriyEtOkou","89624","KoLERUQegIuoRoweliBOgeYuwuOOaeieBopopIJEVAIaToKIa","295","424","ZAXaQIIuiAMOHuNiXAeEkIGATASunINusIVUMAHAvegOeoEuA",14);
INSERT INTO `domicilio` (`altura`,`calle`,`codPostal`,`localidad`,`num_dpto`,`num_piso`,`provincia`,`personaId`) VALUES ("547275","JuMuWOgunuyeXAdAKEbeHavoSeCIvoviIUoonoUANeBiJudII","53417","IAOuQOjEmIwoKAeaAuEuNuVODIEaiomeGEQIqafUaOhOQagoo","055","151","zEhuCARoTuqozUtUlIbozEaeDOqOQUwUrOBETiFuwabAeIvaU",15);
INSERT INTO `domicilio` (`altura`,`calle`,`codPostal`,`localidad`,`num_dpto`,`num_piso`,`provincia`,`personaId`) VALUES ("911943","qiwuFuduzExiBazeIAEodUpoiuBAkoPoZUPEvogamADoQAtAE","84659","yESeTuzAmAKUFExULENOgeEIsEtelUDUwucAqEeaNeuERiGAa","724","035","viMIMODeQAyOGuBijeZaJUYOuUkOSiFaneLaFoOAqupoFIkOO",16);
INSERT INTO `domicilio` (`altura`,`calle`,`codPostal`,`localidad`,`num_dpto`,`num_piso`,`provincia`,`personaId`) VALUES ("932735","OUNEiAMiFiGECAKuWaeEbUJeroYOlOAioOLitOCoIAauuoDuo","56259","daiAsIoAeIzaJICiQuyIiacAKAZOXuYopeoEQEwUTohiMOdua","018","561","AoxOquSikIBAlIHUWOCaIAOaEocODuEIQeeOtoConaneMEPOo",17);
INSERT INTO `domicilio` (`altura`,`calle`,`codPostal`,`localidad`,`num_dpto`,`num_piso`,`provincia`,`personaId`) VALUES ("643666","hireWAloIETEgirUeoAIJUfuwoOErUlIfOoimuROiOpODiJua","10164","hIqaBiVAUUhoVAhIeUVOWENiWOjucuEUiusaPuwUAUkaDovAu","851","226","ZoUAbepufofAcAiEXoporaWeNOSAhAyeSaMedArEoiguiijEu",18);
INSERT INTO `domicilio` (`altura`,`calle`,`codPostal`,`localidad`,`num_dpto`,`num_piso`,`provincia`,`personaId`) VALUES ("811287","oIcaGebERAHOIUFUaiqiSERIxIluvEeuLUQUTuHUSUJouEAio","66212","UILoNIyARilUAoqABUTAteJeCENopimoXuVuNEPUaeAOPuhai","379","311","JiAIQaJOaAEaXOvAjOJIbeVAIaroXUBUbauIYIOAbeougojii",19);
INSERT INTO `domicilio` (`altura`,`calle`,`codPostal`,`localidad`,`num_dpto`,`num_piso`,`provincia`,`personaId`) VALUES ("896216","buRigACESiaifujeHufuBEHeBEMuQiWEgidOvOBuaacIbapoa","17464","MuWePoyuwEDerEOOHagIjenavUmIROLaJOFaMoVUludOJUwIu","999","638","BUdopocoaIXajUGuRaYueIhivoxijiXEPUHENeToGemacejou",20);

INSERT INTO `usuario` (`activo`,`nickname`,`password`,`personaId`) VALUES (1,"xuKASEpUVeboSuOUUEUisiFiWixuGeUoiokoZoJidePilOkie","IUIaKovoTu",1);
INSERT INTO `usuario` (`activo`,`nickname`,`password`,`personaId`) VALUES (0,"BiIIFEBoXOrAEAKouikInOnEqiPeAuwADIwUKUduPAlEwoWah","PuLOjaPoCI",2);
INSERT INTO `usuario` (`activo`,`nickname`,`password`,`personaId`) VALUES (0,"KolEUiCOoOOOjaQIRuxaGOgumExOFoueKoSaLiJUmOmoYumiY","xUzoJeDePU",3);
INSERT INTO `usuario` (`activo`,`nickname`,`password`,`personaId`) VALUES (0,"bIHumUyINUYeyAMeUAXAZekAjULuUEduTIEotocuSORUKiYEp","UiCUoUaUQu",4);
INSERT INTO `usuario` (`activo`,`nickname`,`password`,`personaId`) VALUES (1,"wIYeGoSAriwOgajEBisoAIsalUzeLeOuIUOaNulooANazAQOA","zuyoKoYuJi",5);
INSERT INTO `usuario` (`activo`,`nickname`,`password`,`personaId`) VALUES (0,"FIkUgOCiBUduiErUUoDuYOyutEbEFoquEINoZeUIDEpAcuIOR","WeciqoiOdU",6);
INSERT INTO `usuario` (`activo`,`nickname`,`password`,`personaId`) VALUES (0,"GoOaSirotICadoMiNUFAgEzUtEvewIFenISEcomEWAquwoAoi","zabooeHAGe",7);
INSERT INTO `usuario` (`activo`,`nickname`,`password`,`personaId`) VALUES (1,"AOqoPAyuKErenurioewUOEOOxizAcaxuvAxIWawuJOIuzeFUm","qiDioIuUoI",8);
INSERT INTO `usuario` (`activo`,`nickname`,`password`,`personaId`) VALUES (1,"jaZUpoMuquIaFAhUVIEoqitICEgUyIfuYOvOgOsuDaSeWILeh","bAMERAdeOa",9);
INSERT INTO `usuario` (`activo`,`nickname`,`password`,`personaId`) VALUES (1,"lEsIriDIbIxiTExEWAeoKulitAKejoWOqoVaCumEdOquDAJOC","MiEifUVakA",10);
INSERT INTO `usuario` (`activo`,`nickname`,`password`,`personaId`) VALUES (0,"goyEqOBeweneNUJUjAFINAVolakOyetOAuwoJUuubOmEUoLAL","UekiIoxeTO",11);
INSERT INTO `usuario` (`activo`,`nickname`,`password`,`personaId`) VALUES (0,"tIGoWuJosOXoqEOUwoRUOAxoIAzEKuqaoEouNAmOZoWInAAAe","UIDiviHovU",12);
INSERT INTO `usuario` (`activo`,`nickname`,`password`,`personaId`) VALUES (0,"jUoOiAfefUNOTIXekiSIZazinaauCueIvaiikEaAealuqofib","iajewiSAuI",13);
INSERT INTO `usuario` (`activo`,`nickname`,`password`,`personaId`) VALUES (1,"OioOQaDAdICuCeNuRePogALooebuVuTUsAziXAVEoUeoXoeiS","WAkeCAbaHi",14);
INSERT INTO `usuario` (`activo`,`nickname`,`password`,`personaId`) VALUES (1,"AehISeuIRIlUBiAoUAQAzoFUCiGuUauitiVaooJafAgicIsEW","LegUEEGEqa",15);
INSERT INTO `usuario` (`activo`,`nickname`,`password`,`personaId`) VALUES (0,"XeDuverEUiFOxOAoPIioPoHEoOeAAaJuxuRUFiLoOOLoweyow","AazikOWaqa",16);
INSERT INTO `usuario` (`activo`,`nickname`,`password`,`personaId`) VALUES (0,"zuAIwAVIxoHulegoiareYunadoEIoIiohAnAkASafEWoXoUir","qixAFezOYe",17);
INSERT INTO `usuario` (`activo`,`nickname`,`password`,`personaId`) VALUES (0,"GUDuSihoMUhEkaAuLuuUyEdIXiiAuOKUOEDuLAnUgIJIMIqUm","WUSEZUmEoO",18);
INSERT INTO `usuario` (`activo`,`nickname`,`password`,`personaId`) VALUES (1,"dIWODApuwAJePAGiaAOeFAMooiKErouisobaCuuISOliyopIT","PEharUGIaE",19);
INSERT INTO `usuario` (`activo`,`nickname`,`password`,`personaId`) VALUES (0,"HOFuSinAAOYabiNOZuRocUkiuixiQaPAGoXUhOvioucOpAZUd","kOxEsIDUWo",20);


