INSERT INTO `sub_proyecto`(`Id`, `descripcion`, `detalle`, `titulo`, `proyectoId`)
VALUES (1,' ',' ','Sistema Monitoreo invernáculo',1),
(2,' ',' ','Sistema en Grid para cultivos',2),
(3,' ',' ','CORREL. GEOLÓGICAS Y PALEOMAG',3),
(4,' ',' ','PRODUCCION DE COLZA-CANOLA',4),
(5,' ',' ','DESARROLLO MODULOS CLIMATICOS',5),
(6,' ',' ','Plataforma para ACC',6),
(7,' ',' ','Ce-Bios',7),
(8,' ',' ','Arandu Recursos Biológicos',8),
(9,' ',' ','Predictor de CiberAtacantes',9),
(10,' ',' ','Monitoreo de ganado ovino',10),
(11,' ',' ','Edificios públicos eficientes',11),
(12,' ',' ','TIC EN LA AGROINDUSTRIA',12),
(13,' ',' ','Optimización Valor reciclado',13),
(14,' ',' ','Resiliencia Urbana',14),
(15,' ',' ','Construyendo ciudadanía',15),
(16,' ',' ','Moda y cuerpos disidentes',16),
(17,' ',' ','SUSTENTABILIDAD Y TABACO',17),
(18,' ',' ','Sistema de riego en Azampay',18),
(19,' ',' ','Energía renovable con biomasa',19),
(20,' ',' ','Alperujos y calidad de carne',20),
(21,' ',' ','Colágeno para usos biomédicos',21),
(22,' ',' ','APROVECHAMIENTO DE LACTOSUERO',22),
(23,' ',' ','OpenSIG de Suelos de Córdoba',23),
(24,' ',' ','Nutracéuticos innovadores',24),
(25,' ',' ','SIEECObservatorio emprendedor',25),
(26,' ',' ','Sistema para cultivo orienta',26),
(27,' ',' ','Sistema Monitoreo invernáculo parte dos',1),
(28,' ',' ','Sistema de riego en Azampay parte dos',18)
