delete from persona

insert into persona (tipo,idPersona, nombre) values ('PF',1, 'Normand');
insert into persona (tipo,idPersona, nombre) values ('PF',2, 'Benyamin');
insert into persona (tipo,idPersona, nombre) values ('PF',3, 'Dave');
insert into persona (tipo,idPersona, nombre) values ('PF',4, 'Sidney');
insert into persona (tipo,idPersona, nombre) values ('PF',5, 'Jakob');
insert into persona (tipo,idPersona, nombre) values ('PF',6, 'Hilly');
insert into persona (tipo,idPersona, nombre) values ('PF',7, 'Leonard');
insert into persona (tipo,idPersona, nombre) values ('PF',8, 'Ingra');
insert into persona (tipo,idPersona, nombre) values ('PF',9, 'Phil');
insert into persona (tipo,idPersona, nombre) values ('PF',10, 'Aguie');
insert into persona (tipo,idPersona, nombre) values ('PF',11, 'Daniel');
insert into persona (tipo,idPersona, nombre) values ('PF',12, 'Adolphus');
insert into persona (tipo,idPersona, nombre) values ('PF',13, 'Marcello');
insert into persona (tipo,idPersona, nombre) values ('PF',14, 'Marlow');
insert into persona (tipo,idPersona, nombre) values ('PF',15, 'Chane');
insert into persona (tipo,idPersona, nombre) values ('PF',16, 'Tibold');
insert into persona (tipo,idPersona, nombre) values ('PF',17, 'Erick');
insert into persona (tipo,idPersona, nombre) values ('PF',18, 'Vernor');
insert into persona (tipo,idPersona, nombre) values ('PF',19, 'Yorgo');
insert into persona (tipo,idPersona, nombre) values ('PF',20, 'Guy');

insert into datos_contacto (id, tipo, valor, personaId) values ('1', 'EMAIL', 'arza.isaias@gmail.com', 1);
insert into datos_contacto (id, tipo, valor, personaId) values ('2', 'EMAIL', 'arza.isaias@gmail.com', 2);
insert into datos_contacto (id, tipo, valor, personaId) values ('3', 'EMAIL', 'arza.isaias@gmail.com', 3);
insert into datos_contacto (id, tipo, valor, personaId) values ('4', 'EMAIL', 'arza.isaias@gmail.com', 4);
insert into datos_contacto (id, tipo, valor, personaId) values ('5', 'EMAIL', 'arza.isaias@gmail.com', 5);
insert into datos_contacto (id, tipo, valor, personaId) values ('6', 'EMAIL', 'robertoc.voogt@gmail.com', 6);
insert into datos_contacto (id, tipo, valor, personaId) values ('7', 'EMAIL', 'robertoc.voogt@gmail.com', 7);
insert into datos_contacto (id, tipo, valor, personaId) values ('8', 'EMAIL', 'robertoc.voogt@gmail.com', 8);
insert into datos_contacto (id, tipo, valor, personaId) values ('9', 'EMAIL', 'robertoc.voogt@gmail.com', 9);
insert into datos_contacto (id, tipo, valor, personaId) values ('10', 'EMAIL', 'robertoc.voogt@gmail.com', 10);
insert into datos_contacto (id, tipo, valor, personaId) values ('11', 'EMAIL', 'savarromauricio@gmail.com', 11);
insert into datos_contacto (id, tipo, valor, personaId) values ('12', 'EMAIL', 'savarromauricio@gmail.com', 12);
insert into datos_contacto (id, tipo, valor, personaId) values ('13', 'EMAIL', 'savarromauricio@gmail.com', 13);
insert into datos_contacto (id, tipo, valor, personaId) values ('14', 'EMAIL', 'savarromauricio@gmail.com', 14);
insert into datos_contacto (id, tipo, valor, personaId) values ('15', 'EMAIL', 'savarromauricio@gmail.com', 15);
insert into datos_contacto (id, tipo, valor, personaId) values ('16', 'EMAIL', 'lucasboba@gmail.com', 16);
insert into datos_contacto (id, tipo, valor, personaId) values ('17', 'EMAIL', 'lucasboba@gmail.com', 17);
insert into datos_contacto (id, tipo, valor, personaId) values ('18', 'EMAIL', 'lucasboba@gmail.com', 18);
insert into datos_contacto (id, tipo, valor, personaId) values ('19', 'EMAIL', 'lucasboba@gmail.com', 19);
insert into datos_contacto (id, tipo, valor, personaId) values ('20', 'EMAIL', 'lucasboba@gmail.com', 20);